apiVersion: v1
kind: Service
metadata:
  name: {{ include "pointless-fluentd.fullname" . }}
  labels:
    {{- include "pointless-fluentd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: forward
      protocol: TCP
      name: forward
  selector:
    {{- include "pointless-fluentd.selectorLabels" . | nindent 4 }}
