alertmanager:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    enabled: true
    hosts:
      - alertmanager.spykerman.co.uk
    ingressClassName: nginx
grafana:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    enabled: true
    hosts:
      - grafana.spykerman.co.uk
    ingressClassName: nginx
prometheus:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    enabled: true
    hosts:
      - prometheus.spykerman.co.uk
    ingressClassName: nginx
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels: {}
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector:
      matchLabels: {}
    ruleSelectorNilUsesHelmValues: false
