alertmanager:
  ingress:
    annotations:
      haproxy.org/ssl-redirect: "true"
    enabled: true
    ingressClassName: haproxy
    hosts:
      - alertmanager.spykerman.co.uk
grafana:
  env:
    GF_AUTH_ANONYMOUS_ENABLED: true
    GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    GF_AUTH_DISABLE_LOGIN_FORM: true
  ingress:
    annotations:
      haproxy.org/ssl-redirect: "true"
    enabled: true
    ingressClassName: haproxy
    hosts:
      - grafana.spykerman.co.uk
prometheus:
  ingress:
    annotations:
      haproxy.org/ssl-redirect: "true"
    enabled: true
    ingressClassName: haproxy
    hosts:
      - prometheus.spykerman.co.uk
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels: {}
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleNamespaceSelector:
      matchLabels: {}
    ruleSelectorNilUsesHelmValues: false
